disabled_rules: # rule identifiers to exclude from running
  - todo
  - nesting
  - trailing_comma
opt_in_rules: # some rules are only opt-in
  - empty_count
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
  - Examples/Sources
  - Dangerfile.swift
  - Package.swift
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Examples/Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 120
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
function_body_length:
  warning: 60
  error: 200
file_length:
  warning: 300
  error: 500
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - i
    - j
    - id
    - URL
    - lhs
    - rhs

# ignores switch cases
cyclomatic_complexity:
  ignores_case_statements: true

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
